config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # devise_for :users, :paths => 'user'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
  get '/users', to: 'devise/registrations#new'
  get '/users/password', to: 'devise/passwords#new'
  end
 
  resources :categories do
  resources :tasks
  end

  # config/routes.rb
# devise_scope :user do
#   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
# end

  # resources :categories
  # resources :tasks

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
    belongs_to :category
    validates :task_name, presence: true
    validates :task_description, presence: true
    # validates :task_deadline, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_category
  before_action :set_task, only: %i[ show edit update destroy ]

  # GET /tasks or /tasks.json
  def index
    @tasks = @category.tasks
  end

  # GET /tasks/1 or /tasks/1.json
  def show
    @tasks = @category.tasks
  end

  # GET /tasks/new
  def new
    # @task = Task.new
    @task = @category.tasks.build
  end

  # GET /tasks/1/edit
  def edit
  end

  def patch
  end

  # POST /tasks or /tasks.json
  def create
    @task = @category.tasks.build(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to category_tasks_path(@category), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to category_tasks_path(@category), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to category_tasks_path(@category), notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def get_category
  @category = Category.find(params[:category_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:task_name, :task_description, :task_deadline, :task_done)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with model: [@category,@task], local: true, :html => {:class => "form-signin p-5"} do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-light alert-dismissible fade show alert-fixed" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
        <% task.errors.each do |error| %>
          <p class="small-warning d-inline"><%= error.full_message %> - </p>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :task_name %>
    <%= form.text_field :task_name, class: "form-control" %>
  </div>

  <div class="field mt-2">
    <%= form.label :task_description %>
    <%= form.text_area :task_description, class: "form-control" %>
  </div>

  <div class="field mt-2">
    <%= form.label :task_deadline %>
    <br />
    <%= form.datetime_field :task_deadline %>
  </div>

  <div class="actions">
    <%= form.submit "Create/Update Task", class: "btn btn-lg btn-outline-light btn-block mt-3" %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to ' Back', category_tasks_path, class: "far fa-arrow-alt-circle-left" %>

app/views/tasks/index.html.erb
<div class="container mt-5 ">
<div class="row">
  
  
  <div class="col-lg-3 col-md-4 col-sm-12">
  <div class="sticky-top mt-3">
      <%= image_tag ('mo_task.png'), class: "img-60" %>
      <h1>Categories <i class="fas fa-angle-right"></i> <%=@category.category_name.truncate(40)%></h1>
      <%# <p>MO™ Tasks</p> %>
      <%= link_to ' ', categories_path(current_user.id), class: "far fa-arrow-alt-circle-left btn btn-lg btn-light" %>
      <%= link_to ' Task', new_category_task_path, class: "fas fa-plus btn btn-lg btn-info", id: "addTask" %>
      <hr />
  </div>
  </div>

  <div class="col-sm-12 col-md-8 col-lg-9">
    <table class="table table-hover table-dark table-striped table-bordered">
    
  <thead>
    <tr>
      <th scope="col">Status</th>
      <th scope="col">Task</th>
      <th scope="col">Description</th>
      <th scope="col">Deadline</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @tasks.each do |task| %>
    <tr>
    <% if task.task_done == true %>
      
      <% if task.task_name.size <= 20 %>
        <td>
        <p class="small-warning text-success" style="margin: 0;">Task done!</p>
        <i class="fas fa-check-circle text-success fa-2x" ></i>
        </td>
        <td>
        <div style="word-wrap: break-word;">
        <h6><%= task.task_name %></h6>
        </div>
        </td>
        <% else %>
        <td>
        <p class="small-warning text-success" style="margin: 0;">Task done!</p>
        <i class="fas fa-check-circle text-success fa-2x"></i>
        </td>
        <td>
        <div style="word-wrap: break-word;">
        <h6><%= task.task_name.truncate(20) %><%= link_to 'more', category_task_path(:id => task.id), class: "text-info small-warning" %></h6>
        </div>
        </td>
      <% end %>

    <% else %>
      <td></td>
      <td>
      <div style="word-wrap: break-word;">
      <% if task.task_name.size <= 20 %>
      <h6><%= task.task_name %></h6>
      <% else %>
      <h6><%= task.task_name.truncate(20) %><%= link_to 'more', category_task_path(:id => task.id), class: "text-info small-warning" %></h6>
      <% end %>
      </div>
      </td>
    <% end %>

    <% if task.task_name.size <= 15 %>
      <div style="word-wrap: break-word;">
      <td><%= task.task_description %></td>
      </div>
    <% else %>
      <div style="word-wrap: break-word;">
      <td><%= task.task_description.truncate(15) %> <%= link_to 'more', category_task_path(:id => task.id), class: "text-info" %></td>
      </div>
    <% end %>
    
    <% if task.task_deadline.nil? %>
      <td class="small-warning">N/A</td>
    <% else %>
      <td>
      <p class="small-warning"><%= task.task_deadline.to_formatted_s(:long) %></p>
      </td>
    <% end %>

   
    <td class="d-flex justify-content-between flex-column mx-auto">
       <% if task.task_done == true %>
                <%= button_to "Undone", category_task_path(:id => task.id),   
                params: {:task => { :id => task.id, :task_done => false, :user_id => current_user.id }}, 
                method: :put, class: "btn btn-outline-light btn-sm mb-1 btn-block " %>
                <% else %>
                <%= button_to "Done", category_task_path(:id => task.id),   
                params: {:task => { :id => task.id, :task_done => true, :user_id => current_user.id }}, 
                method: :put, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-primary btn-sm mb-1 btn-block" %>
              <% end %>
      <%= button_to 'Edit', edit_category_task_path(:id => task.id), class: "btn btn-light btn-sm mb-1 btn-block" %>
      <%= link_to ' ', category_task_path(:id => task.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm fas fa-times-circle mb-1 btn-block" %>
    </td>
    </tr>
    <% end %>
  </tbody>
</table>

      
  </div>
  
</div>
</div>


<%= link_to ' Back', categories_path(current_user.id), class: "far fa-arrow-alt-circle-left" %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to ' Back', category_tasks_path, class: "far fa-arrow-alt-circle-left" %>

app/views/tasks/show.html.erb
<div class="card mt-5 bg-dark p-1">
<% if @task.task_done == true %>
  <i class="fas fa-check-circle text-success fa-2x mt-2"></i>
  <p class="small-warning text-success">Task done!</p>
<% end %>
  <h1>Task:</h1>
  <h5 class="card-header"><%= @task.task_name %></h5>
  <div class="card-body">
    <h3>Description:</h3>
    <p class="card-text"><%= @task.task_description %></p>
    <hr />
    <h5 class="card-subtitle mb-2 text-muted small-warning"><strong>Task created at:</strong> <%= @task.created_at.to_formatted_s(:long) %></h5>
    <h5 class="card-subtitle mb-2 text-muted small-warning"><strong>Task updated at:</strong> <%= @task.updated_at.to_formatted_s(:long) %></h5>
    <h5 class="card-subtitle mb-2 text-muted small-warning"><strong>Task deadline:</strong> <%= @task.task_deadline.to_formatted_s(:long) %></h5>
  </div>
</div>

<br />

<%= link_to 'Edit',  edit_category_task_path(@task), class: "card-link btn btn-outline-light btn-lg" %>

<%= link_to 'Ok', category_tasks_path, class: "card-link btn btn-outline-primary btn-lg" %>