config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # devise_for :users, :paths => 'user'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
  get '/users', to: 'devise/registrations#new'
  get '/users/password', to: 'devise/passwords#new'
  end
 
  resources :categories do
  resources :tasks
  end

  # config/routes.rb
# devise_scope :user do
#   delete 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
# end

  # resources :categories
  # resources :tasks

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks

  validates :category_name, presence: true
  validates :category_description, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # before_action :set_category, only: %i[ show edit update destroy ]
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /categories or /categories.json
  def index
    @categories = current_user.categories
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.build(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_path, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @category = current_user.categories.find_by(id: params[:id])
    redirect_to categories_path, notice: "Not Authorized To Edit This Category" if @category.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category_name, :category_description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, :html => {:class => "form-signin p-5"}) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-light alert-dismissible fade show alert-fixed" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
        <% category.errors.each do |error| %>
          <p class="small-warning d-inline"><%= error.full_message %> - </p>
        <% end %>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_name %>
    <%= form.text_field :category_name, class: "form-control" %>
  </div>

  <div class="field mt-2">
    <%= form.label :category_description %>
    <%= form.text_area :category_description, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Create/Update Category", class: "btn btn-lg btn-outline-light btn-block mt-3"  %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form', category: @category %>

<%= link_to ' Back', categories_path, class: "far fa-arrow-alt-circle-left" %>

app/views/categories/index.html.erb
<div class="container mt-5">
  
  <div class="row">
    <div class="col-lg-3 col-md-4 col-sm-12">
    <div class="sticky-top mt-3">
      <%= image_tag ('mo_category.png'), class: "img-60" %>
      <h2>Categories <i class="fas fa-angle-right"></i></h2>
      <%= link_to ' ', root_path, class: "far fa-arrow-alt-circle-left btn btn-lg btn-light" %>
      <%= link_to ' Category', new_category_path(current_user.id), class: "fas fa-plus btn btn-lg btn-info", id: "addCategory"  %>
      <hr />
    </div>
  </div>
  
  <div class="col-sm-12 col-md-8 col-lg-9">
    <div class="container">
      <div class="row mb-3">
      <% if user_signed_in? %>
          <% @categories.each do |category| %>
          <div class="col-sm-12 col-md-12 col-lg-6">
            <div class="card bg-dark border-info text-white mb-4 box-shadow">
              <div class="card-body">

              <% if category.category_name.size <= 60 %>
              <h3 class="card-title" style="font-size: clamp(18px, 4vw, 24px);">Category Name: <%= category.category_name %></h3>
              <% else %>
              <h3 class="card-title" style="font-size: clamp(18px, 4vw, 24px);">Category Name: <%= category.category_name.truncate(60) %> <%= link_to 'more', category_path(category), class: "text-info small-warning" %></h3>
              <% end %>

              <h6 class="card-subtitle mb-2 mb-3">Number of tasks: <%= category.tasks.count %></h6>
              <h6 class="card-subtitle mb-2 text-muted small-warning"><%= category.updated_at.to_formatted_s(:long) %></h6>
              
              <% if category.category_description.size <= 120 %>
              <p class="card-text">Description: <%= category.category_description %></p>
              <% else %>
              <p class="card-text">Description: <%= category.category_description.truncate(120) %> <%= link_to 'more', category_path(category), class: "text-info" %></p>
              <% end %>

              <hr />
              <div class="row d-block text-center">
              <%= link_to ' Tasks', category_tasks_path(category), class: "card-link btn btn-info btn-lg btn-block fas fa-cogs" %>
              <hr />
              </div>
              <div class="row d-inline">
              <%= link_to 'Edit', edit_category_path(category), class: "card-link btn btn-outline-light btn-sm" %>
              <%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-link btn btn-outline-danger btn-sm" %>
              </div>
            </div>
          </div>
      </div>
          <% end %>
      <% end %>
      </div>
      </div>
  </div>
  </div>

</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to ' Back', categories_path, class: "far fa-arrow-alt-circle-left" %>

app/views/categories/show.html.erb
<div class="card mt-5 bg-dark">
  <h5 class="card-header"><%= @category.category_name %></h5>
  <div class="card-body">
    <h5 class="card-subtitle mb-2 text-muted small-warning"><%= @category.updated_at.to_formatted_s(:long) %></h5>
    <p class="card-text"><%= @category.category_description %></p>
  </div>
</div>

<br />

<%= link_to 'Edit', edit_category_path(@category), class: "card-link btn btn-outline-light btn-lg" %>

<%= link_to 'Ok', categories_path, class: "card-link btn btn-outline-primary btn-lg" %>